#!/bin/sh

# exit on any errors
set -e

. ./scripts/vars

LATEST_VERSION="$(./scripts/latest-version)"

if [ -z "${LATEST_VERSION}" ]; then
	echo "no recent alpine tag for docker image ${SOURCE} found"
	exit 0
fi

git clone --no-checkout https://$GITHUB_TOKEN@github.com/$REPO.git dist
cd dist
(git checkout -b dist --track origin/dist || (git checkout --orphan dist && git rm -rf .))

existing_tag="$(git tag -l "$LATEST_VERSION")"

# don't build in cron job when there's already a build for this version
if [ "$TRAVIS_EVENT_TYPE" = "cron" ] && [ ! -z "$existing_tag" ]; then
	echo "build not needed"
	exit 0
fi

(cd ../; scripts/prepare-dist "$LATEST_VERSION")

git config user.email "travis@travis-ci.org"
git config user.name "Travis CI"

if [ ! -z "$existing_tag" ]; then
	git tag -d "$LATEST_VERSION"
	git push --delete origin "$LATEST_VERSION"
fi

git add .
git commit -m "$LATEST_VERSION"
git tag -a "$LATEST_VERSION" -m "$LATEST_VERSION"
git push --follow-tags -u origin dist
