#!/bin/sh

# exit on any errors
set -e

. ./scripts/vars

LATEST_VERSION="$(./scripts/latest-version)"

git clone --no-checkout https://$GITHUB_TOKEN@github.com/$REPO.git dist
cd dist
(git checkout origin/dist || git checkout -b dist)

existing_tag="$(git tag -l "$LATEST_VERSION")"

if [ -z "$existing_tag" ]; then
  (cd ../; scripts/prepare-dist "$LATEST_VERSION")

  git config user.email "travis@travis-ci.org"
  git config user.name "Travis CI"

  git add .
  git commit -m "$LATEST_VERSION"
  git tag -a "$LATEST_VERSION" -m "$LATEST_VERSION"

  git push -u origin dist
fi
